// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarot.Data;

#nullable disable

namespace Tarot.Data.Migrations
{
    [DbContext(typeof(TarotDbContext))]
    partial class TarotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Tarot.Data.CardMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardMeaningId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeaningCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarotCardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeaningCategoryId");

                    b.HasIndex("TarotCardId");

                    b.ToTable("CardMeanings");
                });

            modelBuilder.Entity("Tarot.Data.MeaningCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MeaningCategories");
                });

            modelBuilder.Entity("Tarot.Data.TarotCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TarotCards");
                });

            modelBuilder.Entity("Tarot.Data.CardMeaning", b =>
                {
                    b.HasOne("Tarot.Data.MeaningCategory", "MeaningCategory")
                        .WithMany()
                        .HasForeignKey("MeaningCategoryId");

                    b.HasOne("Tarot.Data.TarotCard", "TarotCard")
                        .WithMany("Meanings")
                        .HasForeignKey("TarotCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeaningCategory");

                    b.Navigation("TarotCard");
                });

            modelBuilder.Entity("Tarot.Data.TarotCard", b =>
                {
                    b.Navigation("Meanings");
                });
#pragma warning restore 612, 618
        }
    }
}
